apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: rg-dev-app
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: koreacentral
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: app-keyvault-9641
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: koreacentral
  owner:
    name: rg-dev-app
    kind: ResourceGroup
  properties:
    tenantId: b1596b6b-3f6e-401c-99ca-a8c96c39eb5e
    sku:
      family: "A"
      name: "standard"
    accessPolicies:
      - tenantId: b1596b6b-3f6e-401c-99ca-a8c96c39eb5e
        objectId: a8ae0cff-426f-43b3-864f-8d478dfd93dd  # User or Service Principal Object ID
        permissions:
          secrets:
            - get
            - list
            - set
    enableSoftDelete: true
